### ISSUE TITLE
Unable to get output from Cisco devices via ssh

### ISSUE THREAD

**Issue by arowden** [google/goexpect#14]
I've had a good experience using this package to ssh into servers. However, I have not been able to get it to work on a Cisco device via ssh yet. The native go ssh package works, but not this one. Since I need to do a few complex tasks, I'd rather use this package if possible.

The first time that I execute e.Expect(promptRE, timeout), it shows the login banner. However, when I send another command and call e.Expect again, the output received is the command I sent. I tried the exact verbose setup from the verbose example and this was the output... 

Match for RE: "Password:" found: ["Password:"] Buffer: Cisco UCS Fabric Interconnect
Password:
Sent: "password\n"
Match for RE: "#" found: ["#"] Buffer:
Cisco Nexus Operating System (NX-OS) Software
TAC support: http://www.cisco.com/tac
Copyright (c) 2009, Cisco Systems, Inc. All rights reserved.
The copyrights to certain works contained in this software are
owned by other third parties and used and distributed under
license. Certain components of this software are licensed under
the GNU General Public License (GPL) version 2.0 or the GNU
Lesser General Public License (LGPL) Version 2.1. A copy of each
such license is available at
http://www.opensource.org/licenses/gpl-2.0.php and
http://www.opensource.org/licenses/lgpl-2.1.php
DEV-1-A#
Sent: "show version\n"
Match for RE: "DEV-1-A#" found: ["DEV-1-A#"] Buffer: show version
DEV-1-A#
cmd: show version: result: show version

The code producing this was...

e.Send("show version\n")
time.Sleep(time.Second)
result, _, _ = e.Expect(promptRE, timeout)
fmt.Println("cmd: %s: result: %s\n", cmd, result)

Please let me know if you have any thoughts on how to fix this. I have already tried playing around with the terminal width and had no luck.

**Comment by ARowden** [comment]
After many hours of digging I was able to find the issue. With Cisco Nexus IOS, the ssh terminal mode has to enable echoing. The solution was to create a terminal with... 

```
func NewTios() term.Termios {
	tios := term.Termios{}
	tios.Raw()
	tios.Lflag = term.ECHO  <------- Enable echo
	tios.Wz.WsCol, tios.Wz.WsRow = sshTermWidth, sshTermHeight
	return tios
}
```

Then pass the terminal to SpawnSSHPTY.

**Comment by skalle** [comment]
Hey ARowden .. Sorry for the way too late reply. 

Sorry for the hours of digging there ... This package has mainly been used for network devices and yes, all vendors have their quirks when it comes to how they handle SSH and terminals. 

From looking at your output the prompt is repeated before the version is printed.. 

```
Match for RE: "DEV-1-A#" found: ["DEV-1-A#"] Buffer: show version
DEV-1-A#
```
Is that the case?

Do you have an example of the logging in and running the `show version` on your device? 

Or if you make the expect RE matching something impossible eg. `\b` and then print the buffer on failure will tell you what expect sees.

See you worked around it with some terminal settings, should be possible to fix this with some tuning of your prompt RE too though, but to help with that I need a session printout from running the command the way you want it to be run.

**Comment by skalle** [comment]
Closing this as it has been stale for quite a while.
