### ISSUE TITLE
Readme assumes too much knowledge

### ISSUE THREAD

**Issue by natefinch** [google/goexpect#2]
The readme isn't useful unless you already know what expect is. If you don't, then it is meaningless (and it's hard to google "expect").

**Comment by skalle** [comment]
Hey natefinch@ . 

Agree with you and I'm working on a new better Readme with examples. 
Will hopefully have some cycles to get it going this Friday ..

**Comment by skalle** [comment]
Also if there is something specific you want to accomplish feel free to update this bug and I'll prio that.

**Comment by skalle** [comment]
https://en.wikipedia.org/wiki/Expect - That's the original TCL expect this is referring to.

**Comment by skalle** [comment]
Hey @natefinch .. 

Some more information added to the README , more work to be done for sure but think we're in a better shape at least.

**Comment by skalle** [comment]
Closing this one down .. 

Feel free to reopen/create new bug if it's still unclear.
