### ISSUE TITLE
Allow ".Run(...)" for a specific command on SSH sessions or expose the session object

### ISSUE THREAD

**Issue by li-lyoung** [google/goexpect#32]
Right now when using [SpawnSSH](https://godoc.org/github.com/google/goexpect#SpawnSSH)/[SpawnSSHPTY](https://godoc.org/github.com/google/goexpect#SpawnSSHPTY) goexpect will create a SSH [Session](https://godoc.org/golang.org/x/crypto/ssh#Session) object and call the [Shell](https://godoc.org/golang.org/x/crypto/ssh#Session.Shell) method automatically. While this works great for lots of network devices, for other devices (ex: servers) it would be great to be able to call the [Run](https://godoc.org/golang.org/x/crypto/ssh#Session.Run) method without creating a shell as that adds additional parsing complexity ($PS1, etc) when you only want to run a single command. I think exporting the underlying [Session](https://godoc.org/golang.org/x/crypto/ssh#Session) object could work or adding the command to run as an [Option](https://godoc.org/github.com/google/goexpect#Option) which would change logic in [SpawnSSHPTY](https://godoc.org/github.com/google/goexpect#SpawnSSHPTY) to call [session.Run](https://godoc.org/golang.org/x/crypto/ssh#Session.Run) instead of [session.Shell](https://godoc.org/golang.org/x/crypto/ssh#Session.Shell) would also work.

**Comment by skalle** [comment]
Hey Li. 

This is partly of how GoExpect came to be, before this we just did session.Run and hoped for the best .. At lest at the time this did not work very well with many, (any?) , of our vendors , even if the command managed to be executed the return codes was quite random. 

Have had requests to expose the session object before but think we went with just using the *ssh.Client to create new session objects to do Run.

**Comment by li-lyoung** [comment]
Thanks for the quick reply @skalle! 
>Have had requests to expose the session object before but think we went with just using the *ssh.Client to create new session objects to do Run.

Do you mean just create your own session object and pass it into [SpawnGeneric](https://godoc.org/github.com/google/goexpect#SpawnGeneric) instead of using the convenience SSH methods?

**Comment by skalle** [comment]
That could probably work but what was done there , don't really remember what they wanted the session for though , was: 

- Create a  ssh.Client.
- Give it to SpawnSSH
- Also use the client to create a separate session, not used at all by expect to do stuff. 

So the expect session is never exposed , another one is created from the client to do whatever was needed there. 

If you really need the expect session for something that'd not work.

**Comment by skalle** [comment]
Hey Li. 

Did that explanation help or you still want to have access to the expect Session object?

**Comment by skalle** [comment]
Closing this as there's been no response for a while, reopen if that's in error.
