### ISSUE TITLE
Tee option does not work with SpawnSSH or SpawnGeneric

### ISSUE THREAD

**Issue by blalor** [google/goexpect#36]
`SpawnSSH` and `SpawnGeneric` both use `waitForSession` which appears to use a different code path than `SpawnWithArgs`, and the output does not pass through `teeWriter`.

**Comment by skalle** [comment]
Hey Brian. 

As I'm pretty swamped atm. I tagged as "help wanted". 
Pull requests welcome.

**Comment by JulienVdG** [comment]
Now that #37 is merged, I think this can be closed.
