### ISSUE TITLE
Go 1.13: Spawn fails with "operation not permitted"

### ISSUE THREAD

**Issue by neild** [google/goexpect#40]
Spawn fails on Go 1.13:

```
$ go run ./examples/process/ 10
F0625 11:06:45.549888  104755 process.go:45] fork/exec /usr/bin/bc: operation not permitted
exit status 1
```

Culprit is https://go-review.googlesource.com/c/go/+/178919 ("syscall: use Ctty before fd shuffle").

If I'm following correctly, the problem is [here](https://github.com/google/goexpect/blob/master/expect.go#L929):

```go
	cmd.SysProcAttr = &syscall.SysProcAttr{
		Setsid:  true,
		Setctty: true}
```

Setting `Setctty` sets the controlling terminal to `SysProcAttr.Ctty`, which is unset (i.e., `0`), which is probably not the desired behavior.

**Comment by neild** [comment]
Not sure whether this is a problem here or in https://go-review.googlesource.com/c/go/+/178919, now that I look at this more closely. Will reopen https://github.com/golang/go/issues/29458 to discuss.

**Comment by skalle** [comment]
Ok cool, I'll hold back for a bit until that's figured out.

**Comment by skalle** [comment]
No updates for a while, closing.
